// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  GetApiAdminInviteCodeData,
  GetApiAdminInviteCodeResponses,
  GetApiAdminOnboardingData,
  GetApiAdminOnboardingResponses,
  GetApiAdminPostsData,
  GetApiAdminPostsResponses,
  GetApiAdminStatsData,
  GetApiAdminStatsResponses,
  GetApiAdminUsersByIdStrikesData,
  GetApiAdminUsersByIdStrikesErrors,
  GetApiAdminUsersByIdStrikesResponses,
  GetApiAdminUsersData,
  GetApiAdminUsersResponses,
  PostApiAdminInviteCodeData,
  PostApiAdminInviteCodeResponses,
  PostApiAdminOnboardingByIdApproveData,
  PostApiAdminOnboardingByIdApproveErrors,
  PostApiAdminOnboardingByIdApproveResponses,
  PostApiAdminOnboardingByIdRejectData,
  PostApiAdminOnboardingByIdRejectErrors,
  PostApiAdminOnboardingByIdRejectResponses,
  PostApiAdminPostsByIdRemoveData,
  PostApiAdminPostsByIdRemoveErrors,
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRestoreData,
  PostApiAdminPostsByIdRestoreErrors,
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeData,
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors,
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses,
  PostApiAdminUsersByIdStrikeData,
  PostApiAdminUsersByIdStrikeErrors,
  PostApiAdminUsersByIdStrikeResponses,
  PostApiAdminUsersByIdSuspendData,
  PostApiAdminUsersByIdSuspendErrors,
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdUnsuspendData,
  PostApiAdminUsersByIdUnsuspendErrors,
  PostApiAdminUsersByIdUnsuspendResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Search users by username or email
 */
export const getApiAdminUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminUsersData, ThrowOnError>,
): RequestResult<GetApiAdminUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminUsersResponses, unknown, ThrowOnError>({
    url: "/api/admin/users",
    ...options,
  })

/**
 * Suspend a user site-wide
 */
export const postApiAdminUsersByIdSuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdSuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdSuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdSuspendResponses,
    PostApiAdminUsersByIdSuspendErrors,
    ThrowOnError
  >({
    url: "/api/admin/users/{id}/suspend",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Lift a user's suspension
 */
export const postApiAdminUsersByIdUnsuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdUnsuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdUnsuspendResponses,
  PostApiAdminUsersByIdUnsuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdUnsuspendResponses,
    PostApiAdminUsersByIdUnsuspendErrors,
    ThrowOnError
  >({ url: "/api/admin/users/{id}/unsuspend", ...options })

/**
 * Issue a site-wide strike against a user, optionally attached to one of their posts or comments. The 5th active strike within 365 days auto-suspends the account.
 */
export const postApiAdminUsersByIdStrike = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdStrikeData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdStrikeResponses,
  PostApiAdminUsersByIdStrikeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdStrikeResponses,
    PostApiAdminUsersByIdStrikeErrors,
    ThrowOnError
  >({
    url: "/api/admin/users/{id}/strike",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Revoke a strike. Does not lift an existing suspension — unsuspend separately if appropriate.
 */
export const postApiAdminUsersByIdStrikeByStrikeIdRevoke = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdStrikeByStrikeIdRevokeData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses,
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses,
    PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors,
    ThrowOnError
  >({ url: "/api/admin/users/{id}/strike/{strikeId}/revoke", ...options })

/**
 * List all strikes for a user, including revoked ones
 */
export const getApiAdminUsersByIdStrikes = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminUsersByIdStrikesData, ThrowOnError>,
): RequestResult<
  GetApiAdminUsersByIdStrikesResponses,
  GetApiAdminUsersByIdStrikesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiAdminUsersByIdStrikesResponses,
    GetApiAdminUsersByIdStrikesErrors,
    ThrowOnError
  >({ url: "/api/admin/users/{id}/strikes", ...options })

/**
 * Search posts by title (includes removed posts)
 */
export const getApiAdminPosts = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminPostsData, ThrowOnError>,
): RequestResult<GetApiAdminPostsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminPostsResponses, unknown, ThrowOnError>({
    url: "/api/admin/posts",
    ...options,
  })

/**
 * Remove a post site-wide (admin)
 */
export const postApiAdminPostsByIdRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRemoveData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRemoveResponses,
    PostApiAdminPostsByIdRemoveErrors,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/remove", ...options })

/**
 * Restore a removed post site-wide (admin)
 */
export const postApiAdminPostsByIdRestore = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRestoreData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminPostsByIdRestoreErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRestoreResponses,
    PostApiAdminPostsByIdRestoreErrors,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/restore", ...options })

/**
 * Site-wide counts overview
 */
export const getApiAdminStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminStatsData, ThrowOnError>,
): RequestResult<GetApiAdminStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminStatsResponses, unknown, ThrowOnError>({
    url: "/api/admin/stats",
    ...options,
  })

/**
 * List onboarding applications for review
 */
export const getApiAdminOnboarding = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminOnboardingData, ThrowOnError>,
): RequestResult<GetApiAdminOnboardingResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminOnboardingResponses, unknown, ThrowOnError>({
    url: "/api/admin/onboarding",
    ...options,
  })

/**
 * Approve an onboarding application, verifying the user
 */
export const postApiAdminOnboardingByIdApprove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminOnboardingByIdApproveData, ThrowOnError>,
): RequestResult<
  PostApiAdminOnboardingByIdApproveResponses,
  PostApiAdminOnboardingByIdApproveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminOnboardingByIdApproveResponses,
    PostApiAdminOnboardingByIdApproveErrors,
    ThrowOnError
  >({ url: "/api/admin/onboarding/{id}/approve", ...options })

/**
 * Reject an onboarding application with a reason
 */
export const postApiAdminOnboardingByIdReject = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminOnboardingByIdRejectData, ThrowOnError>,
): RequestResult<
  PostApiAdminOnboardingByIdRejectResponses,
  PostApiAdminOnboardingByIdRejectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminOnboardingByIdRejectResponses,
    PostApiAdminOnboardingByIdRejectErrors,
    ThrowOnError
  >({
    url: "/api/admin/onboarding/{id}/reject",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List superuser bypass invite codes
 */
export const getApiAdminInviteCode = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminInviteCodeData, ThrowOnError>,
): RequestResult<GetApiAdminInviteCodeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminInviteCodeResponses, unknown, ThrowOnError>({
    url: "/api/admin/invite-code",
    ...options,
  })

/**
 * Create a single-use superuser bypass invite code: redeeming it skips the four-link application and auto-verifies the user
 */
export const postApiAdminInviteCode = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAdminInviteCodeData, ThrowOnError>,
): RequestResult<PostApiAdminInviteCodeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<PostApiAdminInviteCodeResponses, unknown, ThrowOnError>({
    url: "/api/admin/invite-code",
    ...options,
  })
