// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiAdminOnboardingResponse,
  GetApiAdminPostsResponse,
  GetApiAdminUsersResponse,
} from "./types.gen"

export const getApiAdminUsersResponseTransformer = async (
  data: any,
): Promise<GetApiAdminUsersResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    if (item.suspendedAt) {
      item.suspendedAt = new Date(item.suspendedAt)
    }
    return item
  })
  return data
}

export const getApiAdminPostsResponseTransformer = async (
  data: any,
): Promise<GetApiAdminPostsResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.removedAt) {
      item.removedAt = new Date(item.removedAt)
    }
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const getApiAdminOnboardingResponseTransformer = async (
  data: any,
): Promise<GetApiAdminOnboardingResponse> => {
  data.data = data.data.map((item: any) => {
    item.submittedAt = new Date(item.submittedAt)
    if (item.reviewedAt) {
      item.reviewedAt = new Date(item.reviewedAt)
    }
    item.applicant.createdAt = new Date(item.applicant.createdAt)
    return item
  })
  return data
}
