// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3013" | (string & {})
}

export type InnerErrorT = {
  code: string
  innererror?: InnerErrorT
}

export type ErrorObjectT = {
  code:
    | "BadRequest"
    | "Unauthenticated"
    | "Unauthorized"
    | "Forbidden"
    | "NotFound"
    | "MethodNotAllowed"
    | "Conflict"
    | "UnprocessableEntity"
    | "TooManyRequests"
    | "InternalServerError"
    | "ServiceUnavailable"
    | "InsufficientPermissions"
    | "Suspended"
    | "NotVerified"
    | "InviteCodeInvalid"
    | "InviteCodeLimitReached"
    | "AlreadySubmitted"
    | "ValidationFailed"
    | "InvalidInput"
    | "MissingRequiredField"
    | "ResourceNotFound"
    | "ResourceAlreadyExists"
    | "ResourceLocked"
    | "OperationFailed"
    | "ContentStriked"
    | "DataIntegrityViolation"
    | "RateLimitExceeded"
    | string
  message: string
  target?: string
  details?: Array<ErrorObjectT>
  innererror?: InnerErrorT
}

export type ErrorResponseT = {
  error: ErrorObjectT
}

export type GetApiAdminUsersData = {
  body?: never
  path?: never
  query?: {
    q?: string
    cursor?: string
  }
  url: "/api/admin/users"
}

export type GetApiAdminUsersResponses = {
  /**
   * Matching users
   */
  200: {
    data: Array<{
      id: string
      username: string
      email: string
      postKarma: number
      commentKarma: number
      createdAt: Date
      suspendedAt: Date | null
      suspensionReason: string | null
      activeStrikeCount: number
    }>
    nextCursor: string | null
  }
}

export type GetApiAdminUsersResponse = GetApiAdminUsersResponses[keyof GetApiAdminUsersResponses]

export type PostApiAdminUsersByIdSuspendData = {
  body?: {
    reason: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/suspend"
}

export type PostApiAdminUsersByIdSuspendErrors = {
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdSuspendError =
  PostApiAdminUsersByIdSuspendErrors[keyof PostApiAdminUsersByIdSuspendErrors]

export type PostApiAdminUsersByIdSuspendResponses = {
  /**
   * User suspended
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminUsersByIdSuspendResponse =
  PostApiAdminUsersByIdSuspendResponses[keyof PostApiAdminUsersByIdSuspendResponses]

export type PostApiAdminUsersByIdUnsuspendData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/unsuspend"
}

export type PostApiAdminUsersByIdUnsuspendErrors = {
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdUnsuspendError =
  PostApiAdminUsersByIdUnsuspendErrors[keyof PostApiAdminUsersByIdUnsuspendErrors]

export type PostApiAdminUsersByIdUnsuspendResponses = {
  /**
   * User unsuspended
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminUsersByIdUnsuspendResponse =
  PostApiAdminUsersByIdUnsuspendResponses[keyof PostApiAdminUsersByIdUnsuspendResponses]

export type PostApiAdminUsersByIdStrikeData = {
  body?: {
    reason: string
    postId?: string | null
    commentId?: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/strike"
}

export type PostApiAdminUsersByIdStrikeErrors = {
  /**
   * Invalid strike request
   */
  400: ErrorResponseT
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdStrikeError =
  PostApiAdminUsersByIdStrikeErrors[keyof PostApiAdminUsersByIdStrikeErrors]

export type PostApiAdminUsersByIdStrikeResponses = {
  /**
   * Strike issued
   */
  200: {
    id: string
    activeCount: number
    suspended: boolean
  }
}

export type PostApiAdminUsersByIdStrikeResponse =
  PostApiAdminUsersByIdStrikeResponses[keyof PostApiAdminUsersByIdStrikeResponses]

export type PostApiAdminUsersByIdStrikeByStrikeIdRevokeData = {
  body?: never
  path: {
    id: string
    strikeId: string
  }
  query?: never
  url: "/api/admin/users/{id}/strike/{strikeId}/revoke"
}

export type PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors = {
  /**
   * Strike already revoked
   */
  400: ErrorResponseT
  /**
   * Strike not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdStrikeByStrikeIdRevokeError =
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors[keyof PostApiAdminUsersByIdStrikeByStrikeIdRevokeErrors]

export type PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses = {
  /**
   * Strike revoked
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponse =
  PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses[keyof PostApiAdminUsersByIdStrikeByStrikeIdRevokeResponses]

export type GetApiAdminUsersByIdStrikesData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/strikes"
}

export type GetApiAdminUsersByIdStrikesErrors = {
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type GetApiAdminUsersByIdStrikesError =
  GetApiAdminUsersByIdStrikesErrors[keyof GetApiAdminUsersByIdStrikesErrors]

export type GetApiAdminUsersByIdStrikesResponses = {
  /**
   * Strikes for the user
   */
  200: {
    data: Array<{
      id: string
      reason: string
      postId: string | null
      commentId: string | null
      createdAt: Date
      revokedAt: Date | null
      issuedByUsername: string | null
      revokedByUsername: string | null
      active: boolean
    }>
    activeCount: number
  }
}

export type GetApiAdminUsersByIdStrikesResponse =
  GetApiAdminUsersByIdStrikesResponses[keyof GetApiAdminUsersByIdStrikesResponses]

export type GetApiAdminPostsData = {
  body?: never
  path?: never
  query?: {
    q?: string
    cursor?: string
  }
  url: "/api/admin/posts"
}

export type GetApiAdminPostsResponses = {
  /**
   * Matching posts
   */
  200: {
    data: Array<{
      id: string
      title: string
      communityId: string | null
      communityName: string | null
      authorUsername: string | null
      score: number
      removedAt: Date | null
      createdAt: Date
    }>
    nextCursor: string | null
  }
}

export type GetApiAdminPostsResponse = GetApiAdminPostsResponses[keyof GetApiAdminPostsResponses]

export type PostApiAdminPostsByIdRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/posts/{id}/remove"
}

export type PostApiAdminPostsByIdRemoveErrors = {
  /**
   * Post not found
   */
  404: ErrorResponseT
}

export type PostApiAdminPostsByIdRemoveError =
  PostApiAdminPostsByIdRemoveErrors[keyof PostApiAdminPostsByIdRemoveErrors]

export type PostApiAdminPostsByIdRemoveResponses = {
  /**
   * Post removed
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminPostsByIdRemoveResponse =
  PostApiAdminPostsByIdRemoveResponses[keyof PostApiAdminPostsByIdRemoveResponses]

export type PostApiAdminPostsByIdRestoreData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/posts/{id}/restore"
}

export type PostApiAdminPostsByIdRestoreErrors = {
  /**
   * Post not found
   */
  404: ErrorResponseT
}

export type PostApiAdminPostsByIdRestoreError =
  PostApiAdminPostsByIdRestoreErrors[keyof PostApiAdminPostsByIdRestoreErrors]

export type PostApiAdminPostsByIdRestoreResponses = {
  /**
   * Post restored
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminPostsByIdRestoreResponse =
  PostApiAdminPostsByIdRestoreResponses[keyof PostApiAdminPostsByIdRestoreResponses]

export type GetApiAdminStatsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/stats"
}

export type GetApiAdminStatsResponses = {
  /**
   * Counts
   */
  200: {
    users: number
    posts: number
    communities: number
    comments: number
    reportsPending: number
  }
}

export type GetApiAdminStatsResponse = GetApiAdminStatsResponses[keyof GetApiAdminStatsResponses]

export type GetApiAdminOnboardingData = {
  body?: never
  path?: never
  query?: {
    status?: "pending" | "approved" | "rejected"
    cursor?: string
  }
  url: "/api/admin/onboarding"
}

export type GetApiAdminOnboardingResponses = {
  /**
   * Applications with applicant and inviter details
   */
  200: {
    data: Array<{
      id: string
      status: string
      profileLink: string
      opinionLink: string
      criticalThinkingLink: string
      acceptWrongLink: string
      rejectionReason: string | null
      submittedAt: Date
      reviewedAt: Date | null
      applicant: {
        id: string
        username: string
        email: string
        createdAt: Date
      }
      inviter: {
        id: string
        username: string
      } | null
    }>
    nextCursor: string | null
  }
}

export type GetApiAdminOnboardingResponse =
  GetApiAdminOnboardingResponses[keyof GetApiAdminOnboardingResponses]

export type PostApiAdminOnboardingByIdApproveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/onboarding/{id}/approve"
}

export type PostApiAdminOnboardingByIdApproveErrors = {
  /**
   * Application is not pending
   */
  400: ErrorResponseT
}

export type PostApiAdminOnboardingByIdApproveError =
  PostApiAdminOnboardingByIdApproveErrors[keyof PostApiAdminOnboardingByIdApproveErrors]

export type PostApiAdminOnboardingByIdApproveResponses = {
  /**
   * Application approved
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminOnboardingByIdApproveResponse =
  PostApiAdminOnboardingByIdApproveResponses[keyof PostApiAdminOnboardingByIdApproveResponses]

export type PostApiAdminOnboardingByIdRejectData = {
  body?: {
    reason: string
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/onboarding/{id}/reject"
}

export type PostApiAdminOnboardingByIdRejectErrors = {
  /**
   * Application is not pending
   */
  400: ErrorResponseT
}

export type PostApiAdminOnboardingByIdRejectError =
  PostApiAdminOnboardingByIdRejectErrors[keyof PostApiAdminOnboardingByIdRejectErrors]

export type PostApiAdminOnboardingByIdRejectResponses = {
  /**
   * Application rejected
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminOnboardingByIdRejectResponse =
  PostApiAdminOnboardingByIdRejectResponses[keyof PostApiAdminOnboardingByIdRejectResponses]

export type GetApiAdminInviteCodeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/invite-code"
}

export type GetApiAdminInviteCodeResponses = {
  /**
   * Superuser codes with creator and redeemer
   */
  200: {
    data: Array<{
      id: string
      code: string
      createdAt: Date
      usedAt: Date | null
      revokedAt: Date | null
      createdByUsername: string
      usedByUsername: string | null
    }>
  }
}

export type GetApiAdminInviteCodeResponse =
  GetApiAdminInviteCodeResponses[keyof GetApiAdminInviteCodeResponses]

export type PostApiAdminInviteCodeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/invite-code"
}

export type PostApiAdminInviteCodeResponses = {
  /**
   * Superuser code created
   */
  201: {
    id: string
    code: string
    createdAt: Date
  }
}

export type PostApiAdminInviteCodeResponse =
  PostApiAdminInviteCodeResponses[keyof PostApiAdminInviteCodeResponses]
