// Deterministic fallback classifier. Runs when Claude is unavailable, when it declines to answer,
// or when it returns something outside the candidate set.
//
// Community names encode the domain as a suffix (`ChinaTrade`, `USMacro`), so for a country source
// pool the candidates already share a country and the only open question is which domain. That
// keeps the keyword sets small: one per domain, plus one per global topic.

const DOMAIN_TOKENS = [
  "Politics",
  "Governance",
  "Diplomacy",
  "Trade",
  "Macro",
  "Micro",
  "Business",
  "Society",
] as const

type DomainToken = (typeof DOMAIN_TOKENS)[number]

type Weighted = readonly (readonly [string, number])[]

const DOMAIN_KEYWORDS: Record<DomainToken, Weighted> = {
  Politics: [
    ["election", 3],
    ["elections", 3],
    ["electoral", 3],
    ["ballot", 3],
    ["referendum", 3],
    ["parliament", 3],
    ["parliamentary", 3],
    ["congress", 2],
    ["senate", 2],
    ["coalition", 3],
    ["opposition", 2],
    ["party", 2],
    ["candidate", 3],
    ["campaign", 2],
    ["poll", 2],
    ["polls", 2],
    ["voters", 3],
    ["cabinet", 2],
    ["prime minister", 3],
    ["president", 2],
    ["chancellor", 2],
    ["resign", 3],
    ["resignation", 3],
    ["impeachment", 3],
    ["no-confidence", 3],
    ["lawmakers", 2],
  ],
  Governance: [
    ["regulation", 3],
    ["regulator", 3],
    ["regulatory", 3],
    ["ministry", 2],
    ["agency", 2],
    ["court", 3],
    ["ruling", 2],
    ["judiciary", 3],
    ["constitutional", 3],
    ["legislation", 3],
    ["bill", 2],
    ["statute", 2],
    ["bureaucracy", 3],
    ["civil service", 3],
    ["oversight", 3],
    ["watchdog", 2],
    ["corruption", 2],
    ["transparency", 2],
    ["reform", 2],
    ["governance", 3],
    ["rule of law", 3],
    ["audit", 2],
  ],
  Diplomacy: [
    ["summit", 3],
    ["treaty", 3],
    ["sanctions", 3],
    ["ambassador", 3],
    ["embassy", 3],
    ["alliance", 3],
    ["bilateral", 3],
    ["multilateral", 2],
    ["nato", 3],
    ["united nations", 3],
    ["foreign minister", 3],
    ["foreign ministry", 3],
    ["diplomat", 3],
    ["diplomatic", 3],
    ["defence", 2],
    ["defense", 2],
    ["military", 2],
    ["missile", 2],
    ["troops", 2],
    ["ceasefire", 3],
    ["peace talks", 3],
    ["security council", 3],
  ],
  Trade: [
    ["tariff", 3],
    ["tariffs", 3],
    ["export", 3],
    ["exports", 3],
    ["import", 3],
    ["imports", 3],
    ["wto", 3],
    ["supply chain", 3],
    ["semiconductor", 2],
    ["chips", 2],
    ["customs", 3],
    ["trade deal", 3],
    ["trade war", 3],
    ["free trade", 3],
    ["export controls", 3],
    ["dumping", 3],
    ["quota", 2],
    ["industrial policy", 3],
    ["rare earths", 3],
    ["shipping", 2],
    ["port", 1],
  ],
  Macro: [
    ["inflation", 3],
    ["gdp", 3],
    ["central bank", 3],
    ["interest rate", 3],
    ["interest rates", 3],
    ["rate cut", 3],
    ["rate hike", 3],
    ["unemployment", 3],
    ["jobless", 3],
    ["currency", 2],
    ["exchange rate", 3],
    ["deficit", 3],
    ["debt", 2],
    ["budget", 2],
    ["fiscal", 3],
    ["monetary", 3],
    ["recession", 3],
    ["growth forecast", 3],
    ["stimulus", 3],
    ["bond yields", 3],
    ["economy", 1],
  ],
  Micro: [
    ["prices", 2],
    ["price of", 2],
    ["consumer", 2],
    ["consumers", 2],
    ["competition", 3],
    ["antitrust", 3],
    ["monopoly", 3],
    ["labour market", 3],
    ["labor market", 3],
    ["wages", 3],
    ["cost of living", 3],
    ["rent", 2],
    ["housing costs", 3],
    ["households", 3],
    ["productivity", 2],
    ["subsidy", 2],
    ["subsidies", 2],
    ["market failure", 3],
  ],
  Business: [
    ["earnings", 3],
    ["profit", 3],
    ["revenue", 3],
    ["ipo", 3],
    ["merger", 3],
    ["acquisition", 3],
    ["acquires", 3],
    ["takeover", 3],
    ["startup", 3],
    ["shares", 2],
    ["stock", 2],
    ["shareholders", 3],
    ["ceo", 3],
    ["executive", 2],
    ["factory", 2],
    ["chipmaker", 3],
    ["carmaker", 3],
    ["automaker", 3],
    ["bank", 1],
    ["investors", 2],
    ["valuation", 3],
    ["layoffs", 3],
    ["bankruptcy", 3],
  ],
  Society: [
    ["protest", 3],
    ["protests", 3],
    ["culture", 3],
    ["cultural", 3],
    ["education", 3],
    ["school", 2],
    ["university", 2],
    ["students", 2],
    ["migration", 3],
    ["migrants", 3],
    ["immigration", 3],
    ["demographic", 3],
    ["demographics", 3],
    ["birth rate", 3],
    ["ageing", 3],
    ["aging", 3],
    ["religion", 3],
    ["religious", 3],
    ["health", 2],
    ["healthcare", 2],
    ["media", 2],
    ["censorship", 3],
    ["women", 2],
    ["youth", 2],
    ["inequality", 2],
  ],
}

const GLOBAL_TOPIC_KEYWORDS: Record<string, Weighted> = {
  Urbanism: [
    ["urban", 3],
    ["city", 2],
    ["cities", 2],
    ["zoning", 3],
    ["land use", 3],
    ["housing", 3],
    ["density", 3],
    ["sprawl", 3],
    ["walkable", 3],
    ["walkability", 3],
    ["neighborhood", 2],
    ["neighbourhood", 2],
    ["planning", 2],
    ["parking", 3],
    ["street", 2],
    ["streets", 2],
    ["homelessness", 3],
    ["gentrification", 3],
    ["architecture", 2],
    ["public space", 3],
  ],
  Transit: [
    ["transit", 3],
    ["metro", 3],
    ["subway", 3],
    ["rail", 3],
    ["railway", 3],
    ["train", 3],
    ["bus", 3],
    ["buses", 3],
    ["tram", 3],
    ["light rail", 3],
    ["high-speed", 3],
    ["fares", 3],
    ["ridership", 3],
    ["commuter", 3],
    ["bike lane", 3],
    ["cycling", 2],
    ["station", 2],
  ],
  Geopolitics: [
    ["geopolitics", 3],
    ["geopolitical", 3],
    ["war", 3],
    ["conflict", 3],
    ["invasion", 3],
    ["nuclear", 3],
    ["deterrence", 3],
    ["great power", 3],
    ["sphere of influence", 3],
    ["strategic", 2],
    ["rivalry", 3],
    ["military", 2],
    ["sanctions", 2],
    ["security", 2],
  ],
  IntlRelations: [
    ["diplomacy", 3],
    ["diplomatic", 3],
    ["treaty", 3],
    ["alliance", 3],
    ["united nations", 3],
    ["multilateral", 3],
    ["summit", 3],
    ["nato", 2],
    ["g7", 3],
    ["g20", 3],
    ["international law", 3],
    ["bilateral", 2],
    ["foreign policy", 3],
  ],
  GlobalTrade: [
    ["trade", 3],
    ["tariff", 3],
    ["tariffs", 3],
    ["wto", 3],
    ["supply chain", 3],
    ["exports", 2],
    ["imports", 2],
    ["trade deal", 3],
    ["globalisation", 3],
    ["globalization", 3],
    ["shipping", 2],
    ["export controls", 3],
  ],
  Macroeconomics: [
    ["inflation", 3],
    ["gdp", 3],
    ["central bank", 3],
    ["interest rate", 3],
    ["recession", 3],
    ["monetary", 3],
    ["fiscal", 3],
    ["global economy", 3],
    ["imf", 3],
    ["currency", 2],
    ["unemployment", 2],
    ["bond", 2],
  ],
  BalancedViews: [
    ["debate", 2],
    ["opinion", 2],
    ["analysis", 1],
    ["argument", 2],
    ["both sides", 3],
    ["perspective", 2],
    ["viewpoint", 2],
  ],
}

// The registry carries Spanish, French, German and Italian sources. Without these terms the
// fallback classifier scores every one of their headlines at zero, so each article would land in
// the source's default community regardless of subject. Japanese is deliberately absent: it does
// not delimit words with spaces, so the word-boundary matching below cannot work on it.
const DOMAIN_KEYWORDS_INTL: Record<DomainToken, Weighted> = {
  Politics: [
    ["elecciones", 3],
    ["votación", 3],
    ["parlamento", 3],
    ["congreso", 2],
    ["gobierno", 2],
    ["partido", 2],
    ["coalición", 3],
    ["dimisión", 3],
    ["escaños", 3],
    ["élections", 3],
    ["parlement", 3],
    ["gouvernement", 2],
    ["parti", 2],
    ["démission", 3],
    ["Wahl", 3],
    ["Wahlen", 3],
    ["Bundestag", 3],
    ["Regierung", 2],
    ["Koalition", 3],
    ["Rücktritt", 3],
    ["Kanzler", 2],
    ["elezioni", 3],
    ["governo", 2],
    ["partito", 2],
    ["coalizione", 3],
    ["dimissioni", 3],
  ],
  Governance: [
    ["ley", 3],
    ["tribunal", 3],
    ["sentencia", 3],
    ["reforma", 2],
    ["corrupción", 2],
    ["loi", 3],
    ["réforme", 2],
    ["corruption", 2],
    ["décret", 3],
    ["Gesetz", 3],
    ["Gericht", 3],
    ["Urteil", 3],
    ["Reform", 2],
    ["Behörde", 3],
    ["legge", 3],
    ["tribunale", 3],
    ["sentenza", 3],
    ["riforma", 2],
    ["corruzione", 2],
  ],
  Diplomacy: [
    ["cumbre", 3],
    ["tratado", 3],
    ["sanciones", 3],
    ["embajador", 3],
    ["alianza", 3],
    ["exteriores", 3],
    ["sommet", 3],
    ["traité", 3],
    ["ambassadeur", 3],
    ["alliance", 3],
    ["Gipfel", 3],
    ["Vertrag", 2],
    ["Sanktionen", 3],
    ["Botschafter", 3],
    ["Außenminister", 3],
    ["vertice", 3],
    ["trattato", 3],
    ["sanzioni", 3],
    ["ambasciatore", 3],
    ["alleanza", 3],
  ],
  Trade: [
    ["arancel", 3],
    ["aranceles", 3],
    ["exportaciones", 3],
    ["importaciones", 3],
    ["comercio", 2],
    ["exportations", 3],
    ["importations", 3],
    ["commerce", 2],
    ["douane", 3],
    ["Zölle", 3],
    ["Exporte", 3],
    ["Importe", 3],
    ["Handel", 2],
    ["Lieferkette", 3],
    ["dazi", 3],
    ["esportazioni", 3],
    ["importazioni", 3],
    ["commercio", 2],
  ],
  Macro: [
    ["inflación", 3],
    ["banco central", 3],
    ["tipos de interés", 3],
    ["paro", 3],
    ["desempleo", 3],
    ["déficit", 3],
    ["recesión", 3],
    ["pib", 3],
    ["banque centrale", 3],
    ["chômage", 3],
    ["récession", 3],
    ["croissance", 2],
    ["Inflation", 3],
    ["Leitzins", 3],
    ["Arbeitslosigkeit", 3],
    ["Rezession", 3],
    ["Haushalt", 2],
    ["Konjunktur", 3],
    ["inflazione", 3],
    ["banca centrale", 3],
    ["disoccupazione", 3],
    ["recessione", 3],
  ],
  Micro: [
    ["precios", 2],
    ["consumidores", 2],
    ["salarios", 3],
    ["competencia", 3],
    ["alquiler", 3],
    ["prix", 2],
    ["consommateurs", 2],
    ["salaires", 3],
    ["concurrence", 3],
    ["loyer", 3],
    ["Preise", 2],
    ["Verbraucher", 2],
    ["Löhne", 3],
    ["Wettbewerb", 3],
    ["Miete", 3],
    ["prezzi", 2],
    ["consumatori", 2],
    ["salari", 3],
    ["concorrenza", 3],
    ["affitto", 3],
  ],
  Business: [
    ["beneficios", 2],
    ["empresa", 2],
    ["fusión", 3],
    ["bolsa", 3],
    ["acciones", 2],
    ["bénéfices", 2],
    ["entreprise", 2],
    ["fusion", 3],
    ["bourse", 3],
    ["Gewinn", 2],
    ["Unternehmen", 2],
    ["Übernahme", 3],
    ["Aktien", 3],
    ["Börse", 3],
    ["utili", 2],
    ["azienda", 2],
    ["fusione", 3],
    ["borsa", 3],
    ["azioni", 2],
  ],
  Society: [
    // Sport is culture for this taxonomy, and general-news front pages carry a lot of it.
    ["fútbol", 3],
    ["deportes", 3],
    ["liga", 2],
    ["olímpicos", 3],
    ["football", 2],
    ["calcio", 3],
    ["sport", 2],
    ["Fußball", 3],
    ["protesta", 3],
    ["huelga", 3],
    ["educación", 3],
    ["migración", 3],
    ["inmigración", 3],
    ["sanidad", 3],
    ["cultura", 2],
    ["grève", 3],
    ["éducation", 3],
    ["santé", 3],
    ["culture", 2],
    ["Streik", 3],
    ["Bildung", 3],
    ["Migration", 3],
    ["Gesundheit", 3],
    ["Kultur", 2],
    ["sciopero", 3],
    ["istruzione", 3],
    ["migrazione", 3],
    ["sanità", 3],
  ],
}

/** English plus the other registry languages, per domain. Written out so a missing key is a
 * compile error rather than something the fallback silently scores at zero. */
const MERGED_DOMAIN_KEYWORDS = {
  Politics: [...DOMAIN_KEYWORDS.Politics, ...DOMAIN_KEYWORDS_INTL.Politics],
  Governance: [...DOMAIN_KEYWORDS.Governance, ...DOMAIN_KEYWORDS_INTL.Governance],
  Diplomacy: [...DOMAIN_KEYWORDS.Diplomacy, ...DOMAIN_KEYWORDS_INTL.Diplomacy],
  Trade: [...DOMAIN_KEYWORDS.Trade, ...DOMAIN_KEYWORDS_INTL.Trade],
  Macro: [...DOMAIN_KEYWORDS.Macro, ...DOMAIN_KEYWORDS_INTL.Macro],
  Micro: [...DOMAIN_KEYWORDS.Micro, ...DOMAIN_KEYWORDS_INTL.Micro],
  Business: [...DOMAIN_KEYWORDS.Business, ...DOMAIN_KEYWORDS_INTL.Business],
  Society: [...DOMAIN_KEYWORDS.Society, ...DOMAIN_KEYWORDS_INTL.Society],
} satisfies Record<DomainToken, Weighted>

const regexCache = new Map<string, RegExp>()

function keywordRegex(word: string): RegExp {
  const cached = regexCache.get(word)
  if (cached) return cached
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  // \b does not fire next to non-ASCII letters, so guard with explicit boundaries instead.
  const re = new RegExp(`(?:^|[^\\p{L}\\p{N}])${escaped}(?:[^\\p{L}\\p{N}]|$)`, "iu")
  regexCache.set(word, re)
  return re
}

/** The keyword set for a community name: an exact global-topic match, else the domain suffix. */
export function keywordsFor(community: string): Weighted | null {
  const global = GLOBAL_TOPIC_KEYWORDS[community]
  if (global) return global
  const domain = DOMAIN_TOKENS.find((token) => community.endsWith(token))
  return domain ? MERGED_DOMAIN_KEYWORDS[domain] : null
}

export function scoreCommunity(community: string, title: string): number {
  const keywords = keywordsFor(community)
  if (!keywords) return 0
  let score = 0
  for (const [word, weight] of keywords) {
    if (keywordRegex(word).test(title)) score += weight
  }
  return score
}

/**
 * Picks the best community for a title from the source's candidates. Falls back to `fallback`
 * when nothing scores or when the top two tie — an arbitrary tiebreak would be worse than the
 * source's own declared default.
 */
export function classifyByKeyword(
  candidates: readonly string[],
  title: string,
  fallback: string,
): string {
  if (candidates.length === 0) return fallback
  if (candidates.length === 1) return candidates[0]

  const scored = candidates
    .map((community) => ({ community, score: scoreCommunity(community, title) }))
    .toSorted((a, b) => b.score - a.score)

  if (scored[0].score === 0) return fallback
  if (scored.length > 1 && scored[0].score === scored[1].score) return fallback
  return scored[0].community
}
