import { communitiesForCountry } from "./communities"
import type { FeedSource } from "./registry"

// Every feed URL here was fetched and parsed before being added; `docs/feed-registry.md` records
// the verification pass, including the sources that turned out to have no usable feed.
//
// `communities` is the candidate set the classifier may choose from, and `defaultCommunity` is
// where an item lands when nothing decides. A single-entry `communities` skips classification
// entirely, which is why narrow sources are worth keeping narrow.
//
// Sources with `kind: "none"` are never fetched. They stay listed so the next person does not
// spend an afternoon rediscovering that the feed is gone.

const CHINA = communitiesForCountry("China")
const SYRIA = communitiesForCountry("Syria")
const SOUTH_KOREA = communitiesForCountry("SouthKorea")
const NORTH_KOREA = communitiesForCountry("NorthKorea")
const JAPAN = communitiesForCountry("Japan")
// US and UK sources are all section feeds (politics / business / world), so they get explicit
// narrow candidate lists rather than the whole country matrix.
const FRANCE = communitiesForCountry("France")
const GERMANY = communitiesForCountry("Germany")
const ITALY = communitiesForCountry("Italy")
const SPAIN = communitiesForCountry("Spain")
const EU = communitiesForCountry("EU")

export const SOURCE_DATA: FeedSource[] = [
  // ---------------------------------------------------------------- global: urbanism & transit
  {
    id: "streetsblog",
    name: "Streetsblog USA",
    homepage: "https://usa.streetsblog.org",
    kind: "rss",
    feedUrl: "https://usa.streetsblog.org/feed",
    communities: ["Urbanism", "Transit"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "strong-towns",
    name: "Strong Towns",
    homepage: "https://www.strongtowns.org",
    kind: "rss",
    feedUrl: "https://www.strongtowns.org/journal?format=rss",
    communities: ["Urbanism"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "guardian-cities",
    name: "The Guardian — Cities",
    homepage: "https://www.theguardian.com/cities",
    kind: "rss",
    feedUrl: "https://www.theguardian.com/cities/rss",
    communities: ["Urbanism"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "bloomberg-citylab",
    name: "Bloomberg CityLab",
    homepage: "https://www.bloomberg.com/citylab",
    // Every feed path is edge-blocked, but robots.txt advertises news sitemaps that are not.
    // This is the whole Bloomberg news firehose, so the candidate list is wide and the
    // classifier does the narrowing.
    kind: "sitemap",
    feedUrl: "https://www.bloomberg.com/sitemaps/news/latest.xml",
    communities: ["Urbanism", "Transit", "USBusiness", "USMacro", "Macroeconomics"],
    defaultCommunity: "USBusiness",
    language: "en",
  },
  {
    id: "railway-gazette",
    name: "Railway Gazette International",
    homepage: "https://www.railwaygazette.com",
    kind: "rss",
    feedUrl: "https://www.railwaygazette.com/rss",
    communities: ["Transit"],
    defaultCommunity: "Transit",
    language: "en",
  },
  {
    id: "pedestrian-observations",
    name: "Pedestrian Observations",
    homepage: "https://pedestrianobservations.com",
    kind: "rss",
    feedUrl: "https://pedestrianobservations.com/feed/",
    communities: ["Transit", "Urbanism"],
    defaultCommunity: "Transit",
    language: "en",
  },
  {
    id: "yt-not-just-bikes",
    name: "Not Just Bikes (YouTube)",
    homepage: "https://www.youtube.com/@NotJustBikes",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0intLFzLaudFG-xAvUEO-A",
    communities: ["Urbanism", "Transit"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "yt-city-beautiful",
    name: "City Beautiful (YouTube)",
    homepage: "https://www.youtube.com/@CityBeautiful",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCGc8ZVCsrR3dAuhvUbkbToQ",
    communities: ["Urbanism"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "yt-oh-the-urbanity",
    name: "Oh The Urbanity! (YouTube)",
    homepage: "https://www.youtube.com/@OhTheUrbanity",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCN5CBM1NkqDYAHgS-AbgGHA",
    communities: ["Urbanism", "Transit"],
    defaultCommunity: "Urbanism",
    language: "en",
  },
  {
    id: "yt-rmtransit",
    name: "RMTransit (YouTube)",
    homepage: "https://www.youtube.com/@RMTransit",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCf4iKXL_SJQ5d0qsKkboRRQ",
    communities: ["Transit"],
    defaultCommunity: "Transit",
    language: "en",
  },
  {
    id: "yt-alan-fisher",
    name: "Alan Fisher (YouTube)",
    homepage: "https://www.youtube.com/@AlanFisher",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0F_osfA18ZdAqSxAVnKoxQ",
    communities: ["Transit", "Urbanism"],
    defaultCommunity: "Transit",
    language: "en",
  },

  // ------------------------------------------------- global: geopolitics, IR, trade, macro
  {
    id: "war-on-the-rocks",
    name: "War on the Rocks",
    homepage: "https://warontherocks.com",
    kind: "rss",
    feedUrl: "https://warontherocks.com/feed/",
    communities: ["Geopolitics", "IntlRelations"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "foreign-policy",
    name: "Foreign Policy",
    homepage: "https://foreignpolicy.com",
    kind: "rss",
    feedUrl: "https://foreignpolicy.com/feed/",
    communities: ["Geopolitics", "IntlRelations"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "cfr",
    name: "Council on Foreign Relations",
    homepage: "https://www.cfr.org",
    kind: "rss",
    feedUrl: "https://feeds.cfr.org/publication/all",
    communities: ["IntlRelations", "Geopolitics", "USDiplomacy"],
    defaultCommunity: "IntlRelations",
    language: "en",
  },
  {
    id: "csis",
    name: "CSIS",
    homepage: "https://www.csis.org",
    kind: "rss",
    feedUrl: "https://www.csis.org/rss.xml",
    communities: ["Geopolitics", "IntlRelations", "GlobalTrade"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "yt-csis",
    name: "CSIS (YouTube)",
    homepage: "https://www.youtube.com/@csis",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCr5jq6MC_VCe1c5ciIZtk_w",
    communities: ["Geopolitics", "IntlRelations", "GlobalTrade"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "piie",
    name: "Peterson Institute for International Economics",
    homepage: "https://www.piie.com",
    kind: "rss",
    feedUrl: "https://www.piie.com/rss/update.xml",
    communities: ["GlobalTrade", "Macroeconomics"],
    defaultCommunity: "GlobalTrade",
    language: "en",
  },
  {
    id: "project-syndicate",
    name: "Project Syndicate",
    homepage: "https://www.project-syndicate.org",
    kind: "rss",
    feedUrl: "https://www.project-syndicate.org/rss",
    communities: ["BalancedViews", "Macroeconomics", "Geopolitics", "GlobalTrade"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "economist-international",
    name: "The Economist — International",
    homepage: "https://www.economist.com/international",
    kind: "rss",
    feedUrl: "https://www.economist.com/international/rss.xml",
    communities: ["Geopolitics", "IntlRelations", "Macroeconomics", "GlobalTrade"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "ft-world",
    name: "Financial Times — World",
    homepage: "https://www.ft.com/world",
    kind: "rss",
    feedUrl: "https://www.ft.com/world?format=rss",
    communities: ["Geopolitics", "IntlRelations", "GlobalTrade", "Macroeconomics"],
    defaultCommunity: "Geopolitics",
    language: "en",
    notes: "Headlines only; article bodies are paywalled.",
  },
  {
    id: "bbc-world",
    name: "BBC News — World",
    homepage: "https://www.bbc.co.uk/news/world",
    kind: "rss",
    feedUrl: "https://feeds.bbci.co.uk/news/world/rss.xml",
    communities: ["BalancedViews", "IntlRelations", "Geopolitics"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "al-jazeera",
    name: "Al Jazeera English",
    homepage: "https://www.aljazeera.com",
    kind: "rss",
    feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    communities: ["BalancedViews", "Geopolitics", "IntlRelations"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "reuters",
    name: "Reuters",
    homepage: "https://www.reuters.com",
    // Reuters retired its public RSS. This is the news sitemap the index at
    // /news-sitemap-index/ points at — one page of the most recent stories, all of them dated,
    // which is exactly what the 24h filter wants. Do not swap in a Google News proxy: those
    // yield news.google.com redirect links, unusable as permalinks and fatal to URL dedupe.
    kind: "sitemap",
    feedUrl: "https://www.reuters.com/arc/outboundfeeds/news-sitemap/?outputType=xml",
    communities: ["BalancedViews", "Geopolitics", "IntlRelations", "GlobalTrade", "Macroeconomics"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "ap-news",
    name: "Associated Press",
    homepage: "https://apnews.com",
    // index.rss returns 401; the news sitemap does not and carries <news:title> per entry.
    // Broad by nature (sport and entertainment included), hence the wide candidate list.
    kind: "sitemap",
    feedUrl: "https://apnews.com/news-sitemap-content.xml",
    communities: ["BalancedViews", "Geopolitics", "IntlRelations", "USPolitics", "USSociety"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "semafor",
    name: "Semafor",
    homepage: "https://www.semafor.com",
    kind: "rss",
    feedUrl: "https://www.semafor.com/rss.xml",
    communities: ["BalancedViews"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "the-dispatch",
    name: "The Dispatch",
    homepage: "https://thedispatch.com",
    kind: "rss",
    feedUrl: "https://thedispatch.com/feed/",
    communities: ["BalancedViews", "USPolitics", "USSociety"],
    defaultCommunity: "BalancedViews",
    language: "en",
  },
  {
    id: "yt-money-macro",
    name: "Money & Macro (YouTube)",
    homepage: "https://www.youtube.com/@MoneyMacro",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCKpicnIwBP3VPxBAZWDeNA",
    communities: ["Macroeconomics"],
    defaultCommunity: "Macroeconomics",
    language: "en",
  },

  // ------------------------------------------------------------------------------- China
  {
    id: "scmp-china",
    name: "South China Morning Post — China",
    homepage: "https://www.scmp.com/news/china",
    kind: "rss",
    feedUrl: "https://www.scmp.com/rss/4/feed",
    communities: CHINA,
    defaultCommunity: "ChinaPolitics",
    language: "en",
  },
  {
    id: "sixth-tone",
    name: "Sixth Tone",
    homepage: "https://www.sixthtone.com",
    kind: "rss",
    feedUrl: "https://www.sixthtone.com/rss",
    communities: ["ChinaSociety"],
    defaultCommunity: "ChinaSociety",
    language: "en",
  },
  {
    id: "sinocism",
    name: "Sinocism",
    homepage: "https://sinocism.com",
    kind: "rss",
    feedUrl: "https://sinocism.com/feed",
    communities: ["ChinaPolitics", "ChinaGovernance", "ChinaDiplomacy", "ChinaMacro"],
    defaultCommunity: "ChinaPolitics",
    language: "en",
  },
  {
    id: "pekingnology",
    name: "Pekingnology",
    homepage: "https://www.pekingnology.com",
    kind: "rss",
    feedUrl: "https://www.pekingnology.com/feed",
    communities: ["ChinaGovernance", "ChinaPolitics"],
    defaultCommunity: "ChinaGovernance",
    language: "en",
  },
  {
    id: "chinatalk",
    name: "ChinaTalk",
    homepage: "https://www.chinatalk.media",
    kind: "rss",
    feedUrl: "https://www.chinatalk.media/feed",
    communities: ["ChinaBusiness", "ChinaMicro", "ChinaTrade", "ChinaPolitics", "ChinaSociety"],
    defaultCommunity: "ChinaBusiness",
    language: "en",
  },
  {
    id: "yt-chinatalk",
    name: "ChinaTalk (YouTube)",
    homepage: "https://www.youtube.com/@chinatalk",
    kind: "youtube",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCrpsFdM0zyAMsCxjpOXmLmA",
    communities: ["ChinaBusiness", "ChinaTrade", "ChinaPolitics", "ChinaSociety"],
    defaultCommunity: "ChinaBusiness",
    language: "en",
  },
  {
    id: "the-wire-china",
    name: "The Wire China",
    homepage: "https://www.thewirechina.com",
    kind: "rss",
    feedUrl: "https://www.thewirechina.com/feed/",
    communities: ["ChinaBusiness", "ChinaMicro"],
    defaultCommunity: "ChinaBusiness",
    language: "en",
  },
  {
    id: "merics",
    name: "MERICS",
    homepage: "https://merics.org",
    kind: "rss",
    feedUrl: "https://merics.org/en/rss",
    communities: ["ChinaDiplomacy", "ChinaPolitics", "ChinaGovernance", "ChinaTrade"],
    defaultCommunity: "ChinaDiplomacy",
    language: "en",
  },
  {
    id: "nikkei-asia",
    name: "Nikkei Asia",
    homepage: "https://asia.nikkei.com",
    kind: "rss",
    feedUrl: "https://asia.nikkei.com/rss/feed/nar",
    // Genuinely multi-country and multi-domain — the case the classifier exists for.
    communities: [
      "JapanBusiness",
      "JapanMacro",
      "JapanTrade",
      "ChinaBusiness",
      "ChinaTrade",
      "SouthKoreaBusiness",
      "SouthKoreaTrade",
    ],
    defaultCommunity: "JapanBusiness",
    language: "en",
  },

  // ------------------------------------------------------------------------------- Syria
  {
    id: "syria-direct",
    name: "Syria Direct",
    homepage: "https://syriadirect.org",
    kind: "rss",
    feedUrl: "https://syriadirect.org/feed/",
    communities: SYRIA,
    defaultCommunity: "SyriaPolitics",
    language: "en",
  },
  {
    id: "crisis-group",
    name: "International Crisis Group",
    homepage: "https://www.crisisgroup.org",
    kind: "rss",
    feedUrl: "https://www.crisisgroup.org/rss.xml",
    communities: ["Geopolitics", "IntlRelations", "SyriaDiplomacy"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },

  // ------------------------------------------------------------------------- South Korea
  {
    id: "korea-herald",
    name: "The Korea Herald",
    homepage: "https://www.koreaherald.com",
    kind: "rss",
    feedUrl: "https://www.koreaherald.com/rss/newsAll",
    communities: SOUTH_KOREA,
    defaultCommunity: "SouthKoreaPolitics",
    language: "en",
  },
  {
    id: "korea-times",
    name: "The Korea Times",
    homepage: "https://www.koreatimes.co.kr",
    kind: "rss",
    feedUrl: "https://www.koreatimes.co.kr/www/rss/nation.xml",
    communities: SOUTH_KOREA,
    defaultCommunity: "SouthKoreaPolitics",
    language: "en",
    notes: "Sparse feed — often only one item.",
  },
  {
    id: "hankyoreh",
    name: "Hankyoreh (English Edition)",
    homepage: "https://english.hani.co.kr",
    kind: "rss",
    // `/rss` and `/rss/` both serve the KOREAN all-articles feed despite the english. subdomain;
    // only `/rss/english_edition` is the English edition. Neither carries a date element, so the
    // parser falls back to the /YYYY/MMDD/ stamp in each item's thumbnail URL.
    feedUrl: "https://english.hani.co.kr/rss/english_edition",
    communities: ["SouthKoreaPolitics", "SouthKoreaSociety", "SouthKoreaGovernance"],
    defaultCommunity: "SouthKoreaPolitics",
    language: "en",
  },

  // ------------------------------------------------------------------------- North Korea
  {
    id: "nk-news",
    name: "NK News",
    homepage: "https://www.nknews.org",
    kind: "rss",
    feedUrl: "https://www.nknews.org/feed/",
    communities: NORTH_KOREA,
    defaultCommunity: "NorthKoreaPolitics",
    language: "en",
  },
  {
    id: "38-north",
    name: "38 North",
    homepage: "https://www.38north.org",
    kind: "rss",
    feedUrl: "https://www.38north.org/feed/",
    communities: [
      "NorthKoreaDiplomacy",
      "NorthKoreaPolitics",
      "NorthKoreaGovernance",
      "NorthKoreaMacro",
    ],
    defaultCommunity: "NorthKoreaDiplomacy",
    language: "en",
  },
  {
    id: "daily-nk",
    name: "Daily NK (English)",
    homepage: "https://www.dailynk.com/english/",
    kind: "rss",
    feedUrl: "https://www.dailynk.com/english/feed/",
    communities: ["NorthKoreaSociety", "NorthKoreaMicro", "NorthKoreaBusiness"],
    defaultCommunity: "NorthKoreaSociety",
    language: "en",
  },

  // ------------------------------------------------------------------------------- Japan
  {
    id: "japan-times",
    name: "The Japan Times",
    homepage: "https://www.japantimes.co.jp",
    kind: "rss",
    feedUrl: "https://www.japantimes.co.jp/feed/",
    communities: JAPAN,
    defaultCommunity: "JapanPolitics",
    language: "en",
  },
  {
    id: "asahi-shimbun",
    name: "Asahi Shimbun",
    homepage: "https://www.asahi.com",
    kind: "rss",
    feedUrl: "https://www.asahi.com/rss/asahi/newsheadlines.rdf",
    communities: ["JapanPolitics", "JapanSociety", "JapanGovernance"],
    defaultCommunity: "JapanPolitics",
    language: "ja",
  },

  // ----------------------------------------------------------------------- United States
  {
    id: "nyt-world",
    name: "The New York Times — World",
    homepage: "https://www.nytimes.com/section/world",
    kind: "rss",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    communities: ["Geopolitics", "IntlRelations", "USDiplomacy"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "nyt-politics",
    name: "The New York Times — Politics",
    homepage: "https://www.nytimes.com/section/politics",
    kind: "rss",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
    communities: ["USPolitics", "USGovernance"],
    defaultCommunity: "USPolitics",
    language: "en",
  },
  {
    id: "nyt-business",
    name: "The New York Times — Business",
    homepage: "https://www.nytimes.com/section/business",
    kind: "rss",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    communities: ["USBusiness", "USMacro", "USMicro"],
    defaultCommunity: "USBusiness",
    language: "en",
  },
  {
    id: "politico",
    name: "Politico",
    homepage: "https://www.politico.com",
    kind: "rss",
    feedUrl: "https://rss.politico.com/politics-news.xml",
    communities: ["USPolitics", "USGovernance"],
    defaultCommunity: "USPolitics",
    language: "en",
  },
  {
    id: "vox",
    name: "Vox",
    homepage: "https://www.vox.com",
    kind: "rss",
    feedUrl: "https://www.vox.com/rss/index.xml",
    communities: ["USSociety", "USPolitics", "USMicro"],
    defaultCommunity: "USSociety",
    language: "en",
  },
  {
    id: "the-atlantic",
    name: "The Atlantic",
    homepage: "https://www.theatlantic.com",
    kind: "rss",
    feedUrl: "https://www.theatlantic.com/feed/all/",
    communities: ["USSociety", "USPolitics"],
    defaultCommunity: "USSociety",
    language: "en",
  },
  {
    id: "national-review",
    name: "National Review",
    homepage: "https://www.nationalreview.com",
    kind: "rss",
    feedUrl: "https://www.nationalreview.com/feed/",
    communities: ["USPolitics", "USSociety"],
    defaultCommunity: "USPolitics",
    language: "en",
  },
  {
    id: "aei",
    name: "American Enterprise Institute",
    homepage: "https://www.aei.org",
    kind: "rss",
    feedUrl: "https://www.aei.org/feed/",
    communities: ["USGovernance", "USPolitics", "USMacro", "USSociety"],
    defaultCommunity: "USGovernance",
    language: "en",
  },
  {
    id: "federal-reserve",
    name: "Federal Reserve — press releases",
    homepage: "https://www.federalreserve.gov",
    kind: "rss",
    feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
    communities: ["USMacro"],
    defaultCommunity: "USMacro",
    language: "en",
  },

  // ---------------------------------------------------------------------- United Kingdom
  {
    id: "bbc-uk-politics",
    name: "BBC News — Politics",
    homepage: "https://www.bbc.co.uk/news/politics",
    kind: "rss",
    feedUrl: "https://feeds.bbci.co.uk/news/politics/rss.xml",
    communities: ["UKPolitics", "UKGovernance"],
    defaultCommunity: "UKPolitics",
    language: "en",
  },
  {
    id: "guardian-business",
    name: "The Guardian — Business",
    homepage: "https://www.theguardian.com/uk/business",
    kind: "rss",
    feedUrl: "https://www.theguardian.com/uk/business/rss",
    communities: ["UKBusiness", "UKMacro", "UKMicro"],
    defaultCommunity: "UKBusiness",
    language: "en",
  },
  {
    id: "telegraph-news",
    name: "The Telegraph — News",
    homepage: "https://www.telegraph.co.uk/news/",
    kind: "rss",
    feedUrl: "https://www.telegraph.co.uk/news/rss.xml",
    communities: ["UKPolitics", "UKSociety", "UKGovernance"],
    defaultCommunity: "UKPolitics",
    language: "en",
  },
  {
    id: "institute-for-government",
    name: "Institute for Government",
    homepage: "https://www.instituteforgovernment.org.uk",
    kind: "rss",
    feedUrl: "https://www.instituteforgovernment.org.uk/rss.xml",
    communities: ["UKGovernance"],
    defaultCommunity: "UKGovernance",
    language: "en",
  },
  {
    id: "bank-of-england",
    name: "Bank of England — news",
    homepage: "https://www.bankofengland.co.uk",
    kind: "rss",
    feedUrl: "https://www.bankofengland.co.uk/rss/news",
    communities: ["UKMacro"],
    defaultCommunity: "UKMacro",
    language: "en",
  },

  // ------------------------------------------------------------------------------ France
  {
    id: "le-monde",
    name: "Le Monde — Une",
    homepage: "https://www.lemonde.fr",
    kind: "rss",
    feedUrl: "https://www.lemonde.fr/rss/une.xml",
    communities: FRANCE,
    defaultCommunity: "FrancePolitics",
    language: "fr",
  },
  {
    id: "le-monde-international",
    name: "Le Monde — International",
    homepage: "https://www.lemonde.fr/international/",
    kind: "rss",
    feedUrl: "https://www.lemonde.fr/international/rss_full.xml",
    communities: ["FranceDiplomacy", "Geopolitics", "IntlRelations"],
    defaultCommunity: "FranceDiplomacy",
    language: "fr",
  },
  {
    id: "le-figaro",
    name: "Le Figaro",
    homepage: "https://www.lefigaro.fr",
    kind: "rss",
    feedUrl: "https://www.lefigaro.fr/rss/figaro_actualites.xml",
    communities: ["FrancePolitics", "FranceSociety", "FranceGovernance"],
    defaultCommunity: "FrancePolitics",
    language: "fr",
  },
  {
    id: "liberation",
    name: "Libération",
    homepage: "https://www.liberation.fr",
    kind: "rss",
    feedUrl: "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
    communities: ["FrancePolitics", "FranceSociety"],
    defaultCommunity: "FrancePolitics",
    language: "fr",
  },
  {
    id: "france24-en",
    name: "France 24 (English)",
    homepage: "https://www.france24.com/en/",
    kind: "rss",
    feedUrl: "https://www.france24.com/en/rss",
    communities: ["Geopolitics", "IntlRelations", "FrancePolitics", "FranceDiplomacy"],
    defaultCommunity: "Geopolitics",
    language: "en",
  },
  {
    id: "ifri",
    name: "IFRI",
    homepage: "https://www.ifri.org",
    kind: "rss",
    feedUrl: "https://www.ifri.org/en/rss.xml",
    communities: ["FranceDiplomacy", "Geopolitics", "IntlRelations"],
    defaultCommunity: "FranceDiplomacy",
    language: "en",
  },

  // ----------------------------------------------------------------------------- Germany
  {
    id: "der-spiegel",
    name: "Der Spiegel",
    homepage: "https://www.spiegel.de",
    kind: "rss",
    feedUrl: "https://www.spiegel.de/schlagzeilen/tops/index.rss",
    communities: GERMANY,
    defaultCommunity: "GermanyPolitics",
    language: "de",
  },
  {
    id: "sueddeutsche",
    name: "Süddeutsche Zeitung",
    homepage: "https://www.sueddeutsche.de",
    kind: "rss",
    feedUrl: "https://rss.sueddeutsche.de/rss/Topthemen",
    communities: ["GermanyPolitics", "GermanyGovernance", "GermanySociety"],
    defaultCommunity: "GermanyPolitics",
    language: "de",
  },
  {
    id: "faz",
    name: "Frankfurter Allgemeine Zeitung",
    homepage: "https://www.faz.net",
    kind: "rss",
    feedUrl: "https://www.faz.net/rss/aktuell/",
    communities: GERMANY,
    defaultCommunity: "GermanyPolitics",
    language: "de",
  },
  {
    id: "die-zeit",
    name: "Die Zeit",
    homepage: "https://www.zeit.de",
    kind: "rss",
    feedUrl: "https://newsfeed.zeit.de/index",
    communities: ["GermanySociety", "GermanyPolitics"],
    defaultCommunity: "GermanySociety",
    language: "de",
  },
  {
    id: "dw-english",
    name: "Deutsche Welle (English)",
    homepage: "https://www.dw.com/en/",
    kind: "rss",
    feedUrl: "https://rss.dw.com/rdf/rss-en-all",
    communities: ["GermanyPolitics", "GermanyDiplomacy", "GermanySociety", "Geopolitics"],
    defaultCommunity: "GermanyPolitics",
    language: "en",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    homepage: "https://www.handelsblatt.com",
    kind: "rss",
    feedUrl: "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    communities: ["GermanyBusiness", "GermanyMacro", "GermanyMicro", "GermanyTrade"],
    defaultCommunity: "GermanyBusiness",
    language: "de",
  },

  // ------------------------------------------------------------------------------- Italy
  {
    id: "corriere",
    name: "Corriere della Sera",
    homepage: "https://www.corriere.it",
    kind: "rss",
    feedUrl: "https://xml2.corriereobjects.it/rss/homepage.xml",
    communities: ITALY,
    defaultCommunity: "ItalyPolitics",
    language: "it",
  },
  {
    id: "la-repubblica",
    name: "La Repubblica",
    homepage: "https://www.repubblica.it",
    kind: "rss",
    feedUrl: "https://www.repubblica.it/rss/homepage/rss2.0.xml",
    communities: ["ItalyPolitics", "ItalySociety", "ItalyGovernance"],
    defaultCommunity: "ItalyPolitics",
    language: "it",
  },
  {
    id: "il-sole-24-ore",
    name: "Il Sole 24 Ore",
    homepage: "https://www.ilsole24ore.com",
    kind: "rss",
    feedUrl: "https://www.ilsole24ore.com/rss/italia.xml",
    communities: ["ItalyBusiness", "ItalyMacro", "ItalyMicro", "ItalyTrade"],
    defaultCommunity: "ItalyBusiness",
    language: "it",
  },
  {
    id: "la-stampa",
    name: "La Stampa",
    homepage: "https://www.lastampa.it",
    // Every RSS path answers 308 forever, but robots.txt advertises a news sitemap that works.
    kind: "sitemap",
    feedUrl: "https://www.lastampa.it/sitemap-n.xml",
    communities: ["ItalyPolitics", "ItalySociety", "ItalyGovernance"],
    defaultCommunity: "ItalyPolitics",
    language: "it",
  },
  {
    id: "sky-tg24",
    name: "Sky TG24",
    homepage: "https://tg24.sky.it",
    kind: "rss",
    feedUrl: "https://tg24.sky.it/rss/tg24.xml",
    communities: ["ItalyPolitics", "ItalySociety"],
    defaultCommunity: "ItalyPolitics",
    language: "it",
  },

  // ------------------------------------------------------------------------------- Spain
  {
    id: "el-pais",
    name: "El País",
    homepage: "https://elpais.com",
    kind: "rss",
    feedUrl: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    communities: SPAIN,
    defaultCommunity: "SpainPolitics",
    language: "es",
  },
  {
    id: "el-mundo",
    name: "El Mundo",
    homepage: "https://www.elmundo.es",
    kind: "rss",
    feedUrl: "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
    communities: ["SpainPolitics", "SpainGovernance", "SpainSociety"],
    defaultCommunity: "SpainPolitics",
    language: "es",
  },
  {
    id: "abc-es",
    name: "ABC",
    homepage: "https://www.abc.es",
    kind: "rss",
    feedUrl: "https://www.abc.es/rss/2.0/portada/",
    communities: ["SpainPolitics", "SpainSociety"],
    defaultCommunity: "SpainPolitics",
    language: "es",
  },
  {
    id: "la-vanguardia",
    name: "La Vanguardia",
    homepage: "https://www.lavanguardia.com",
    kind: "rss",
    feedUrl: "https://www.lavanguardia.com/rss/home.xml",
    communities: ["SpainSociety", "SpainPolitics"],
    defaultCommunity: "SpainSociety",
    language: "es",
  },
  {
    id: "expansion",
    name: "Expansión",
    homepage: "https://www.expansion.com",
    kind: "rss",
    feedUrl: "https://e00-expansion.uecdn.es/rss/portada.xml",
    communities: ["SpainBusiness", "SpainMacro", "SpainMicro", "SpainTrade"],
    defaultCommunity: "SpainBusiness",
    language: "es",
  },
  {
    id: "elcano",
    name: "Elcano Royal Institute",
    homepage: "https://www.realinstitutoelcano.org",
    kind: "rss",
    feedUrl: "https://www.realinstitutoelcano.org/en/feed/",
    communities: ["SpainDiplomacy", "Geopolitics", "IntlRelations"],
    defaultCommunity: "SpainDiplomacy",
    language: "en",
  },

  // ---------------------------------------------------------------------- European Union
  {
    id: "politico-europe",
    name: "Politico Europe",
    homepage: "https://www.politico.eu",
    kind: "rss",
    feedUrl: "https://www.politico.eu/feed/",
    communities: EU,
    defaultCommunity: "EUPolitics",
    language: "en",
  },
  {
    id: "euobserver",
    name: "EUobserver",
    homepage: "https://euobserver.com",
    kind: "rss",
    feedUrl: "https://euobserver.com/rss",
    communities: ["EUGovernance", "EUPolitics", "EUSociety"],
    defaultCommunity: "EUGovernance",
    language: "en",
  },
  {
    id: "bruegel",
    name: "Bruegel",
    homepage: "https://www.bruegel.org",
    kind: "rss",
    feedUrl: "https://www.bruegel.org/rss.xml",
    communities: ["EUMacro", "EUTrade", "EUMicro", "EUGovernance"],
    defaultCommunity: "EUMacro",
    language: "en",
  },
  {
    id: "ecfr",
    name: "European Council on Foreign Relations",
    homepage: "https://ecfr.eu",
    kind: "rss",
    feedUrl: "https://ecfr.eu/feed/",
    communities: ["EUDiplomacy", "Geopolitics", "IntlRelations"],
    defaultCommunity: "EUDiplomacy",
    language: "en",
  },
  {
    id: "ecb-press",
    name: "European Central Bank — press",
    homepage: "https://www.ecb.europa.eu",
    kind: "rss",
    feedUrl: "https://www.ecb.europa.eu/rss/press.html",
    communities: ["EUMacro"],
    defaultCommunity: "EUMacro",
    language: "en",
  },
  {
    id: "eu-commission",
    name: "European Commission — press corner",
    homepage: "https://ec.europa.eu/commission/presscorner/",
    kind: "rss",
    feedUrl: "https://ec.europa.eu/commission/presscorner/api/rss?language=en",
    communities: ["EUGovernance", "EUPolitics", "EUTrade"],
    defaultCommunity: "EUGovernance",
    language: "en",
  },

  // ------------------------------------------------------- known-unusable (never fetched)
  // Kept so the next person does not rediscover these the hard way. See docs/feed-registry.md.
  {
    id: "planetizen",
    name: "Planetizen",
    homepage: "https://www.planetizen.com",
    kind: "none",
    communities: ["Urbanism"],
    defaultCommunity: "Urbanism",
    language: "en",
    notes: "rss.xml returns 403 regardless of user agent.",
  },
  {
    id: "lawfare",
    name: "Lawfare",
    homepage: "https://www.lawfaremedia.org",
    kind: "none",
    communities: ["USGovernance"],
    defaultCommunity: "USGovernance",
    language: "en",
    notes: "Feed returns 403 regardless of user agent.",
  },
  {
    id: "brookings",
    name: "Brookings Institution",
    homepage: "https://www.brookings.edu",
    kind: "none",
    communities: ["USGovernance", "USDiplomacy"],
    defaultCommunity: "USGovernance",
    language: "en",
    notes:
      "Advertises /feed/ in its <link rel=alternate> but serves HTML to non-browser clients. robots.txt does list sitemap_index.xml, and article-sitemap.xml returns 998 URLs — but with no <news:title>, so there are no headlines to post.",
  },
  {
    id: "chatham-house",
    name: "Chatham House",
    homepage: "https://www.chathamhouse.org",
    kind: "none",
    communities: ["UKDiplomacy", "IntlRelations"],
    defaultCommunity: "UKDiplomacy",
    language: "en",
    notes: "All feed paths return 403; no feed advertised in page metadata.",
  },
  {
    id: "carnegie-endowment",
    name: "Carnegie Endowment for International Peace",
    homepage: "https://carnegieendowment.org",
    kind: "none",
    communities: ["IntlRelations", "Geopolitics"],
    defaultCommunity: "IntlRelations",
    language: "en",
    notes: "Site rebuilt on Next.js; no feed advertised and legacy /rss paths serve HTML.",
  },
  {
    id: "euractiv",
    name: "Euractiv",
    homepage: "https://www.euractiv.com",
    kind: "none",
    communities: ["EUGovernance", "EUPolitics"],
    defaultCommunity: "EUGovernance",
    language: "en",
    notes: "Feed returns 403 regardless of user agent.",
  },
  {
    id: "east-asia-forum",
    name: "East Asia Forum",
    homepage: "https://eastasiaforum.org",
    kind: "none",
    communities: ["SouthKoreaGovernance", "JapanGovernance"],
    defaultCommunity: "SouthKoreaGovernance",
    language: "en",
    notes: "Feed returns 403 regardless of user agent.",
  },
  {
    id: "enab-baladi",
    name: "Enab Baladi (English)",
    homepage: "https://english.enabbaladi.net",
    kind: "none",
    communities: SYRIA,
    defaultCommunity: "SyriaSociety",
    language: "en",
    notes: "Feed returns 403 regardless of user agent.",
  },
  {
    id: "middle-east-institute",
    name: "Middle East Institute",
    homepage: "https://www.mei.edu",
    kind: "none",
    communities: ["SyriaDiplomacy", "SyriaMacro"],
    defaultCommunity: "SyriaDiplomacy",
    language: "en",
    notes: "rss.xml returns 403.",
  },
  {
    id: "les-echos",
    name: "Les Echos",
    homepage: "https://www.lesechos.fr",
    kind: "none",
    communities: ["FranceBusiness", "FranceMacro"],
    defaultCommunity: "FranceBusiness",
    language: "fr",
    notes: "All feed paths return 403.",
  },
  {
    id: "ispi",
    name: "ISPI",
    homepage: "https://www.ispionline.it",
    kind: "none",
    communities: ["ItalyDiplomacy"],
    defaultCommunity: "ItalyDiplomacy",
    language: "en",
    notes: "/en/feed returns 200 but contains no entries.",
  },
  {
    id: "cinco-dias",
    name: "Cinco Días",
    homepage: "https://cincodias.elpais.com",
    kind: "none",
    communities: ["SpainBusiness", "SpainMacro"],
    defaultCommunity: "SpainBusiness",
    language: "es",
    notes: "Feed returns 403 while the sibling El País feed does not.",
  },
  {
    id: "the-times",
    name: "The Times",
    homepage: "https://www.thetimes.com",
    kind: "none",
    communities: ["UKPolitics", "UKBusiness"],
    defaultCommunity: "UKPolitics",
    language: "en",
    notes:
      "/uk/rss returns 200 with no items. robots.txt lists /sitemaps/news, which parses but carried a single entry — too thin to be worth polling.",
  },
  {
    id: "politicshome",
    name: "PoliticsHome",
    homepage: "https://www.politicshome.com",
    kind: "none",
    communities: ["UKPolitics"],
    defaultCommunity: "UKPolitics",
    language: "en",
    notes:
      "/rss returns 404. robots.txt lists sitemap.xml (530 URLs) but it carries no <news:title>, so there are no headlines to post.",
  },
  {
    id: "swp-berlin",
    name: "SWP Berlin",
    homepage: "https://www.swp-berlin.org",
    kind: "none",
    communities: ["GermanyDiplomacy"],
    defaultCommunity: "GermanyDiplomacy",
    language: "en",
    notes: "Publication feed path returns 404.",
  },
  {
    id: "kiel-institute",
    name: "Kiel Institute for the World Economy",
    homepage: "https://www.ifw-kiel.de",
    kind: "none",
    communities: ["GermanyTrade", "GermanyMacro"],
    defaultCommunity: "GermanyTrade",
    language: "en",
    notes: "/rss/ returns 404.",
  },
  {
    id: "korea-joongang-daily",
    name: "Korea JoongAng Daily",
    homepage: "https://koreajoongangdaily.joins.com",
    kind: "none",
    communities: SOUTH_KOREA,
    defaultCommunity: "SouthKoreaPolitics",
    language: "en",
    notes: "Legacy XML feed path returns 404.",
  },
]
